FROM ubuntu:22.04

#ubuntu안에 nginx 직접 설치
RUN apt-get update && \
    apt-get install -y nginx && \
    rm -rf /var/lib/apt/lists/*


#내 컴퓨터의 HTML파일을 컨테이너 안의 NGINX 기본 웹 루트로 복사
COPY src/index.html /var/www/html/index.html

EXPOSE 80
#NGINX가 백그라운드로 빠지지 않고 컨테이너의 메인 프로세스로
#계속 실행
#deamon off: 메인프로세스인 NGINX가 백이 아닌 포그라운드에서 실행유지
#컨테이너 유지를 위해서
CMD ["nginx", "-g", "daemon off;"]